// Generated by CoffeeScript 1.6.2
var letter, open_letter;

letter = function(spec, that) {
  var create, inheriter, p;

  that = that != null ? that : {};
  p = palantir(spec);
  create = p.route('init', function() {
    p.template('header.html', $('#header'));
    p.template('body.html', $('#body'), that);
    return p.template('footer.html', $('#footer'));
  });
  setTimeout((function() {
    return create();
  }), 0);
  inheriter = _.partial(init, letter, that, spec);
  return that;
};

open_letter = letter({
  base_url: 'http://localhost:8000/'
});
